### ISSUE TITLE
Link to BRT example on website is broken

### ISSUE THREAD

**Issue by tpoisot** [GEO-BON/bon-in-a-box-pipelines#201]
See e.g. 

https://pipelines-results.geobon.org/viewer/SDM%3ESDM_BRT%3Ed519bfe0fa3489f28738763dced7ceb0

No map, no artifacts, no nothing

**Comment by jmlord** [comment]
Link above is one of the buttons on top of https://boninabox.geobon.org/indicator?i=SDM

**Comment by tpoisot** [comment]
yeah, sorry, should have mentionned that - @glaroc @gottacatchenall is this an old build and not the most recent one?

**Comment by jmlord** [comment]
Resolved. The problem was actually that there was no results for this run on pipelines-2, and that this server was temporarily used when result server ran out of space.

pipelines-results is up and much stricter than before, since I have activated options that prevent from modifying or running any pipelines on this instance.
