### ISSUE TITLE
Clearer documentation about the 'pipeline engine'

### ISSUE THREAD

**Issue by simonrolph** [GEO-BON/bon-in-a-box-pipelines#62]
Hi, I watched the BON in a Box webinar here: https://www.youtube.com/watch?v=6QHSX1Y70ss and have found your github for the code. I have looked at your readme, on the website and delved a bit into the code but I am unclear about the 'pipeline engine' that is mentioned in the webinar. 

There are lots of existing pipeline tools such as snakemake, airflow, galaxy etc. and I can't work out if your 'pipeline engine' is using an existing tool in the back end or is completely bespoke? I see that Ansible is mentioned but is that part of the pipelines or just setting up the webserver? I'm just unclear how things like parallel processing, transfer to HPC etc. is handled.

A bit more clarity in the readme would be helpful. Many thanks!

**Comment by jmlord** [comment]
Hi Simon,

Thanks for you interest in this project. We indeed plan to have a much more complete documentation by the official launch in October during the [GEO BON Global Conference](https://event.fourwaves.com/geobon-2023). So yes, please suggest modifications where info is lacking or when facing hurdles like you just did. :)

We unfortunately (and to our surprise) had to create our own pipeline engine since none of the ones we looked at matched our requirements. Notably: being open, bridging between R, Julia and Python, providing the results live as things progress, allow to deploy anywhere on a server or personal computer, etc. The pipeline engine code is in the script-server folder.

Ansible is only used for setting up the servers.

HPC: Our current support for HPC is by writing a script that calls an HPC's API. In other words, it can be used inside a step. None of our pipelines currently use that however. Though we had discussions for some platform-based HPC support, no solution was chosen yet. If you'd like to be part of further discussions let us know!

Parallel processing: if a pipeline has multiple branches, they are run in parallel. Parallelization can also occur inside the step's code, such as when using the maxent package. We were thinking to add Swarm or Kubernetes on top of it, but we have not faced problems yet by letting the OS handle it natively.

Let me know if the above answered your question. I'll add about HPC and parallel processing to the readme.

**Comment by jmlord** [comment]
The pipeline engine is now in a separate repo: https://github.com/GEO-BON/bon-in-a-box-pipeline-engine

The user launching the server does not have to worry about docker anymore besides installing it: `./server-up.sh` and `./server-down.sh` are used and handle the docker commands.

About HPC, feature request was added here: https://github.com/GEO-BON/bon-in-a-box-pipeline-engine/issues/7

**Comment by jmlord** [comment]
The pipeline engine is now in a separate repo: https://github.com/GEO-BON/bon-in-a-box-pipeline-engine

The user launching the server does not have to worry about docker anymore besides installing it: ./server-up.sh and ./server-down.sh are used and handle the docker commands.

About HPC, feature request was added here: https://github.com/GEO-BON/bon-in-a-box-pipeline-engine/issues/7
